name: release

permissions:
  pull-requests: write
  contents: write

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'release/**'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: install bevy dependencies
        shell: bash
        run: sudo apt-get update && sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - name: run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
